from app.models import Bakery
from app.review_analyzer import extract_tags

_RAW_BAKERIES = [
    {
        "id": 1,
        "name": "파리바게뜨 문정법조타운점",
        "address": "문정동 642-3",
        "mood": ["편안한", "모던한"],
        "purpose": ["브런치", "선물"],
        "signature_menu": "버터크루아상",
        "price_range": "중가",
        "rating": 4.0,
        "description": "언제나 믿을 수 있는 동네 빵집",
        "parking": True,
        "custom_order": False,
        "distance": 0.2,
        "reviews": [
            "크루아상이 바삭하고 맛있어요",
            "선물용으로 포장도 예쁘게 해줘요",
            "주차 편하고 접근성 좋아요",
        ],
    },
    {
        "id": 2,
        "name": "뚜레쥬르 문정역점",
        "address": "문정동 55-7",
        "mood": ["편안한"],
        "purpose": ["브런치", "빵구경"],
        "signature_menu": "생크림케이크",
        "price_range": "중가",
        "rating": 3.9,
        "description": "다양한 빵이 매일 신선하게 나오는 곳",
        "parking": False,
        "custom_order": True,
        "distance": 0.1,
        "reviews": [
            "케이크 주문 제작이 가능해요",
            "빵 종류가 정말 다양해요",
            "생일 케이크 맡기기 좋아요",
        ],
    },
    {
        "id": 3,
        "name": "밀도 문정점",
        "address": "문정동 290-1",
        "mood": ["모던한", "감성적인"],
        "purpose": ["빵구경", "선물"],
        "signature_menu": "소금빵",
        "price_range": "고가",
        "rating": 4.7,
        "description": "줄 서서 먹는 소금빵 명소",
        "parking": False,
        "custom_order": False,
        "distance": 0.8,
        "reviews": [
            "소금빵이 진짜 맛있어요 꼭 드세요",
            "항상 웨이팅이 있지만 기다릴 가치 있어요",
            "선물용으로도 최고예요",
        ],
    },
    {
        "id": 4,
        "name": "봄봄 베이커리",
        "address": "문정동 101-5",
        "mood": ["아늑한", "감성적인"],
        "purpose": ["브런치", "모임"],
        "signature_menu": "리코타 치즈 토스트",
        "price_range": "중가",
        "rating": 4.4,
        "description": "로컬 감성 가득한 브런치 베이커리",
        "parking": False,
        "custom_order": False,
        "distance": 0.5,
        "reviews": [
            "브런치 메뉴가 너무 맛있어요",
            "아늑하고 따뜻한 분위기예요",
            "토스트와 샌드위치가 맛있어요",
        ],
    },
    {
        "id": 5,
        "name": "르뱅 문정",
        "address": "문정동 78-12",
        "mood": ["빈티지한", "아늑한"],
        "purpose": ["빵구경", "선물"],
        "signature_menu": "통밀 캄파뉴",
        "price_range": "고가",
        "rating": 4.5,
        "description": "천연 발효종으로 만드는 정통 아티잔 빵",
        "parking": True,
        "custom_order": False,
        "distance": 1.1,
        "reviews": [
            "바게트와 식빵이 정말 맛있어요",
            "빵 퀄리티가 최고예요",
            "포근한 분위기에서 빵 고르는 재미가 있어요",
        ],
    },
    {
        "id": 6,
        "name": "크루아상하우스 문정",
        "address": "문정동 33-9",
        "mood": ["모던한"],
        "purpose": ["빵구경", "브런치"],
        "signature_menu": "버터 크루아상 세트",
        "price_range": "중가",
        "rating": 4.2,
        "description": "크루아상 전문 베이커리",
        "parking": False,
        "custom_order": False,
        "distance": 0.3,
        "reviews": [
            "크루아상이 정말 바삭해요",
            "버터 향이 진해서 맛있어요",
            "가성비 좋은 빵집이에요",
        ],
    },
    {
        "id": 7,
        "name": "마리 케이크 문정",
        "address": "문정동 150-3",
        "mood": ["감성적인", "아늑한"],
        "purpose": ["케이크", "선물", "모임"],
        "signature_menu": "딸기 생크림 케이크",
        "price_range": "고가",
        "rating": 4.6,
        "description": "정성껏 만드는 주문 제작 케이크 전문점",
        "parking": True,
        "custom_order": True,
        "distance": 1.5,
        "reviews": [
            "케이크가 너무 예쁘고 맛있어요",
            "생일 케이크 주문 제작 강추해요",
            "선물용 박스도 예쁘게 해줘요",
        ],
    },
    {
        "id": 8,
        "name": "땅콩베이커리 문정",
        "address": "문정동 212-8",
        "mood": ["편안한"],
        "purpose": ["빵구경", "브런치"],
        "signature_menu": "땅콩버터 식빵",
        "price_range": "저가",
        "rating": 4.1,
        "description": "동네 단골들의 가성비 빵집",
        "parking": False,
        "custom_order": False,
        "distance": 0.6,
        "reviews": [
            "가성비가 최고예요",
            "저렴한데 맛있어요",
            "식빵이 맛있고 매일 와요",
        ],
    },
]


def _build_bakeries() -> list[Bakery]:
    bakeries = []
    for raw in _RAW_BAKERIES:
        tags = extract_tags(raw["reviews"])
        bakeries.append(Bakery(**raw, tags=tags))
    return bakeries


BAKERIES: list[Bakery] = _build_bakeries()
